apiVersion: apps/v1
kind: Deployment
metadata:
  name: furniture-deployment
  labels:
    app: furniture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: furniture
  template:
    metadata:
      labels:
        app: furniture
    spec:
      containers:
      - name: furniture
        image: 905418452515.dkr.ecr.us-east-1.amazonaws.com/shopping-site-furniture:43a716cfcc62424b10e88b6caa38b02e43709651
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: furniture-service
  labels:
    app: furniture
spec:
  type: ClusterIP
  selector:
    app: furniture
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
