apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 314429811329.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlemusic:b55712abcb2050916de358bf7cefc10bfeaf9e50
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: googlemusic-service
  labels:
    app: googlemusic
spec:
  type: ClusterIP
  selector:
    app: googlemusic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
