apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 314429811329.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlepay:8f7280909deac8f25c6259fd769d507b3ef6f830
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: googlepay-service
  labels:
    app: googlepay
spec:
  type: ClusterIP
  selector:
    app: googlepay
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
