apiVersion: apps/v1
kind: Deployment
metadata:
  name: sports-deployment
  labels:
    app: sports
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sports
  template:
    metadata:
      labels:
        app: sports
    spec:
      containers:
      - name: sports
        image: 891377149147.dkr.ecr.us-east-1.amazonaws.com/shopping-site-sports:dec055f95b9aa18d7cd9ab34a38e9be08ee7d7b1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sports-service
  labels:
    app: sports
spec:
  type: ClusterIP
  selector:
    app: sports
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
