apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-deployment
  labels:
    app: auto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto
  template:
    metadata:
      labels:
        app: auto
    spec:
      containers:
      - name: auto
        image: 574635351066.dkr.ecr.us-east-1.amazonaws.com/shopping-site-auto:1aa27f58c6019f2817f3d4c3a5018b7e46f8ca10
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: auto-service
  labels:
    app: auto
spec:
  type: ClusterIP
  selector:
    app: auto
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
