apiVersion: apps/v1
kind: Deployment
metadata:
  name: appliances-deployment
  labels:
    app: appliances
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appliances
  template:
    metadata:
      labels:
        app: appliances
    spec:
      containers:
      - name: appliances
        image: 044755820328.dkr.ecr.us-east-1.amazonaws.com/shopping-site-appliances:f040a15561da379ab50d3a278e32ace3cb753b3a
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: appliances-service
  labels:
    app: appliances
spec:
  type: ClusterIP
  selector:
    app: appliances
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
