name: infra Terraform

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  TF_VERSION: "1.12.2"
  TF_WORKING_DIR: EKS-Terraform
  BUCKET_NAME: hitesh-eks-cloud-2026  

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform-version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: |
          cd ${{ env.TF_WORKING_DIR }}
          terraform init -backend-config="bucket=${{ env.BUCKET_NAME }}"

      - name: Terraform Validate
        run: |
          cd ${{ env.TF_WORKING_DIR }}
          terraform validate

      - name: Terraform Plan
        run: |
          cd ${{ env.TF_WORKING_DIR }}
          terraform plan

      - name: Terraform Apply
        run: |
          cd ${{ env.TF_WORKING_DIR }}
          terraform apply -auto-approve
